# Generated by Django 3.1.3 on 2020-12-13 14:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarPark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_name', models.CharField(max_length=100)),
                ('airport_id', models.CharField(max_length=100)),
                ('image', models.TextField(max_length=10000)),
                ('car_park_name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('dis_capacity', models.IntegerField()),
                ('normal_capacity', models.IntegerField()),
                ('tw_capacity', models.IntegerField()),
                ('is_long_term', models.BooleanField()),
            ],
            options={
                'db_table': 'CarPark',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(default='', max_length=30)),
                ('discount_percent', models.IntegerField()),
            ],
            options={
                'db_table': 'Discounts',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('password', models.CharField(default='', max_length=1000)),
                ('email', models.CharField(default='', max_length=50, unique=True, validators=[django.core.validators.EmailValidator()])),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=50, validators=[django.core.validators.EmailValidator()])),
                ('is_old', models.BooleanField(default=False)),
                ('is_logged_in', models.BooleanField(default=False)),
                ('car_wash', models.BooleanField(default=False)),
                ('is_handicap', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('total_cost', models.FloatField()),
                ('is_two_wheeler', models.BooleanField(default=False)),
                ('alphanumeric_string', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('car_park', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='airpark_app.carpark')),
            ],
            options={
                'db_table': 'Bookings',
            },
        ),
    ]
