# Generated by Django 3.1.2 on 2020-11-09 16:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarPark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_name', models.CharField(max_length=100)),
                ('image', models.TextField(max_length=10000)),
                ('car_park_name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('total_spots', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('password', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50, unique=True, validators=[django.core.validators.EmailValidator()])),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_start_date', models.DateTimeField()),
                ('booking_end_date', models.DateTimeField()),
                ('total_cost', models.FloatField()),
                ('duration_type', models.IntegerField()),
                ('alphanumeric_string', models.CharField(max_length=100)),
                ('car_park_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airpark_app.carpark')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airpark_app.user')),
            ],
        ),
    ]
