# Generated by Django 3.1.2 on 2020-10-24 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airpark_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Bookings',
        ),
        migrations.RenameModel(
            old_name='CarPark',
            new_name='CarParks',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
