# Generated by Django 3.1.3 on 2020-11-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpark_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.IntegerField()),
                ('discount_percent', models.IntegerField()),
            ],
        ),
    ]
