# Generated by Django 3.1.2 on 2020-11-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpark_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
