# Generated by Django 3.1.2 on 2020-11-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpark_app', '0002_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpark',
            name='max_capacity',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carpark',
            name='max_dis_capacity',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
