# Generated by Django 3.1.2 on 2020-10-24 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airpark_app', '0002_auto_20201024_2025'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookings',
            new_name='Booking',
        ),
        migrations.RenameModel(
            old_name='CarParks',
            new_name='CarPark',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
