# Generated by Django 3.1.2 on 2020-12-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpark_app', '0003_auto_20201129_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpark',
            name='max_tw_capacity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
