# Generated by Django 3.1.2 on 2020-11-08 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpark_app', '0003_auto_20201024_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=50, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
