# Generated by Django 3.1.2 on 2020-12-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpark_app', '0004_carpark_max_tw_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpark',
            name='airport_id',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
