# Generated by Django 3.1.2 on 2020-11-08 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airpark_app', '0005_auto_20201108_1534'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
    ]
