# Generated by Django 3.1.3 on 2020-12-05 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airpark_app', '0006_carpark_is_long_term'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carpark',
            old_name='max_capacity',
            new_name='dis_capacity',
        ),
        migrations.RenameField(
            model_name='carpark',
            old_name='max_dis_capacity',
            new_name='normal_capacity',
        ),
        migrations.RenameField(
            model_name='carpark',
            old_name='max_tw_capacity',
            new_name='tw_capacity',
        ),
        migrations.RemoveField(
            model_name='carpark',
            name='total_spots',
        ),
        migrations.AlterModelTable(
            name='booking',
            table='Bookings',
        ),
        migrations.AlterModelTable(
            name='carpark',
            table='CarPark',
        ),
        migrations.AlterModelTable(
            name='discount',
            table='Discounts',
        ),
    ]
