# Generated by Django 3.1.3 on 2020-12-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpark_app', '0008_auto_20201205_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user_id',
            new_name='user_email',
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_percent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(default='', max_length=30),
        ),
    ]
