# Generated by Django 3.1.3 on 2020-12-05 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpark_app', '0009_auto_20201205_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user_email',
            field=models.CharField(default='', max_length=50, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
